### ISSUE TITLE
删水印

### ISSUE THREAD

**Issue by theflash12138** [holk-h/recorded-of-Jing#2]
你能把带别人水印的截掉么

**Comment by holk-h** [comment]
可以但是没必要

**Comment by theflash12138** [comment]
那是我的水印------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;holk&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月16日(星期一) 晚上8:19
收件人:&nbsp;&quot;holk-h/recorded-of-Jing&quot;<recorded-of-Jing@noreply.github.com&gt;;
抄送:&nbsp;&quot;theflash12138&quot;<2847015984@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [holk-h/recorded-of-Jing] 删水印 (#2)
